[project]
name = "runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=11.8.0",
    "ansible-runner>=2.4.1",
    "q>=2.7",
]
